### ISSUE TITLE
Re-elect: Oren Novotny

### ISSUE THREAD

**Issue by clairernovotny** [dotnet-foundation/election#1]
---
title: Oren Novotny
layout: default
---

# .NET Foundation Campaign: Oren Novotny

## Why I'm Running
I am currently a member of the board and the Foundation's de facto CISO. I am also a Microsoft [Regional Director](https://rd.microsoft.com/en-us/oren-novotny), [MVP](https://mvp.microsoft.com/en-us/PublicProfile/5000913?fullName=Oren%20Novotny), and Chief Architect of DevOps & Modern Software at [Insight](https://www.insight.com/en_US/solve/digital-innovation.html).   Over the past several years, I have served on the Foundation's Advisory Council and am the author and of its [code signing service](https://github.com/onovotny/SignService). I am passionate about helping projects succeed and am a big believer of secure, and fully automated DevOps. To that end, I run the Foundation's Azure DevOps org and have helped almost all of the current projects onboard with their build system and add code signing. I also helped the Foundation establish a partnership with [DigiCert](https://www.digicert.com/) to enable these services.

I aim to continue to help projects with their DecSecOps needs, running and evolving the code signing services, and driving the growth of the .NET ecosystem.

## My .NET Contributions

I am the author of, or maintainer of, many open source projects. Some of the better known:

- [Reactive Extensions for .NET](https://github.com/dotnet/reactive) (includes Ix Async)
- [xUnit](https://github.com/xunit) (Device runner and Visual Studio test adapter)
- [Humanizer](https://github.com/Humanizr/Humanizer)
- [Windows Community Toolkit](https://github.com/windows-toolkit/WindowsCommunityToolkit)
- [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer)

I also speak at various conferences on topics including .NET Core, Code Signing, and Azure AD B2C.

## Links
* [My blog](https://oren.codes)
* [Regional Director profile](https://rd.microsoft.com/en-us/oren-novotny)
* [MVP profile](https://mvp.microsoft.com/en-us/PublicProfile/5000913?fullName=Oren%20Novotny)

## Contact Information
* Twitter: [@onovotny](https://twitter.com/onovotny)
* GitHub: [@onovotny](https://github.com/onovotny)

**Comment by jongalloway** [comment]
Merged in https://github.com/dotnet-foundation/election/commit/eb80d14c4b49b3709ecafaed72a346174ca6a744

**Comment by ghuntley** [comment]
Oren has my vote and sword
