### ISSUE TITLE
Candidate Twitter list

### ISSUE THREAD

**Issue by jongalloway** [dotnet-foundation/election#108]
We had a suggestion to create a Twitter list of candidates so people can follow them more easily. I'm happy to create that list under the @dotnetfdn Twitter account.

I think there might be a slick way to parse these from the Markdown files, or it could be done by hand. I can probably do that if things cool down after the election, but if anyone wants to create a list of Twitter handles and reply on this thread, that'd be even better and fasterer.

**Comment by daveaglick** [comment]
[@sh4na](https://twitter.com/sh4na)
[@andrey_akinshin](https://twitter.com/andrey_akinshin)
[@antoine_hy](https://twitter.com/antoine_hy)
[@ben_a_adams](https://twitter.com/ben_a_adams)
[@daronyondem](https://twitter.com/daronyondem)
[@daveaglick](https://twitter.com/daveaglick)
[@dierufdavid](https://twitter.com/dierufdavid)
[@davidpine7](https://twitter.com/davidpine7)
[@eric_sink](https://twitter.com/eric_sink)
[@erikschierboom](https://twitter.com/erikschierboom)
[@gep13](https://twitter.com/gep13)
[@gcaughey](https://twitter.com/gcaughey)
[@irisclasson](https://twitter.com/irisclasson)
[@tidusjar](https://twitter.com/tidusjar)
[@JessPWhite](https://twitter.com/JessPWhite)
[@jonskeet](https://twitter.com/jonskeet)
[@jguadagno](https://twitter.com/jguadagno)
[@lucecarter1](https://twitter.com/lucecarter1)
[@mairacw](https://twitter.com/mairacw)
[@MarcBruins](https://twitter.com/MarcBruins)
[@Mpdreamz](https://twitter.com/Mpdreamz)
[@devlead](https://twitter.com/devlead)
[@mjhutchinson](https://twitter.com/mjhutchinson)
[@mitchelsellers](https://twitter.com/mitchelsellers)
[@dotMorten](https://twitter.com/dotMorten)
[@nata_dzen](https://twitter.com/nata_dzen)
[@nbarbettini](https://twitter.com/nbarbettini)
[@onovotny](https://twitter.com/onovotny)
[@p_mbanugo](https://twitter.com/p_mbanugo)
[@haacked](https://twitter.com/haacked)
[@K2Prk](https://twitter.com/K2Prk)
[@robertmclaws](https://twitter.com/robertmclaws)
[@lakritzator](https://twitter.com/lakritzator)
[@rdiazconcha](https://twitter.com/rdiazconcha)
[@samidip](https://twitter.com/samidip)
[@SaraJChipps](https://twitter.com/SaraJChipps)
[@sjkilleen](https://twitter.com/sjkilleen)
[@sbwalker](https://twitter.com/sbwalker)
[@schneidenbach](https://twitter.com/schneidenbach)
[@stefanov_](https://twitter.com/stefanov_)
[@stevejgordon](https://twitter.com/stevejgordon)
[@sahuwanya](https://twitter.com/sahuwanya)
[@dotnetlagos](https://twitter.com/dotnetlagos)
[@tonerdo](https://twitter.com/tonerdo)
[@xen2](https://twitter.com/xen2)

If you want to do it again (I had to do a little manual cleanup to remove false positives):
```
var regex = new Regex("https?:\\/\\/.*twitter.com\\/([a-zA-Z0-9_]{1,15})");
string usernames = string.Join(Environment.NewLine, Directory
	.EnumerateFiles(@"C:\Code\election\_campaign-2019")
	.Select(x => File.ReadAllText(x))
	.SelectMany(x => regex.Matches(x).Cast<Match>().Select(m => m.Groups[1].Value))
	.Distinct()
	.Select(x => $"[@{x}](https://twitter.com/{x})"));
```

**Comment by SeanKilleen** [comment]
Edit -- @daveaglick beat me to it, with a better method too! :)

**Comment by daveaglick** [comment]
![](https://media0.giphy.com/media/pALw8LdftuqAw/giphy.gif)

**Comment by jongalloway** [comment]
https://twitter.com/dotnetfdn/lists/candidates-2019
