### ISSUE TITLE
[WIP] Geoffrey Huntley

### ISSUE THREAD

**Issue by ghuntley** [dotnet-foundation/election#12]
Opening early 👷🚧👷‍♀️ when [WIP] is removed it's ready to ⛴️

```
What does the .NET Foundation Board Do?
The board completely runs the .NET Foundation. They decide how the money is spent, what projects join the foundation, what the Executive Director does, what programs the foundation will run or be involved with, what events we’ll sponsor. The board runs the foundation.
```

---
title: Geoffrey Huntley
layout: default
---

# .NET Foundation Campaign: Geoffrey Huntley

## Why I'm Running
(Describe why you want to get involved. What would you like the .NET Foundation 
to do more of, or do differently?)

## My .NET Contributions
(Let us know who you are. Don't worry if you're not famous, or a huge open source 
contributor - we'd like a variety of experiences.)

## Links
* [My blog](https://dotnetfoundation.org/blog)
* [A project I contribute to](link here)
* [A Meetup I help run](link here)

## Contact Information
* Twitter: [@geoffreyhuntley](https://twitter.com/geoffreyhuntley)
* GitHub: [@ghuntley](https://github.com/ghuntley)

**Comment by jongalloway** [comment]
Closing since Geoffrey said he's not going to be running, ping if you want to re-open.
