### ISSUE TITLE
Marc Bruins

### ISSUE THREAD

**Issue by MarcBruins** [dotnet-foundation/election#17]
# .NET Foundation Campaign: Marc Bruins

<img alt="Marc Bruins" src="https://avatars3.githubusercontent.com/u/676025?s=200&u=d27539adff79207311f2090aff5baae13e663ec5&v=4">

Hi! I am Marc, a 28-year-old cheesehead(aka Dutch) who likes to think of himself as an open source caretaker.

## TL;DR
* My *[mission](#mission)* is to help maintainers lighten the burden, every minute that we can save for a maintainer is a win!
* I have a *[passion](#passion)* for building and growing open source projects
* In my limited years of *[experience](#experience)* I have been active in open source with whole my heart

`Don't elect me for experience, elect me for my energy, intrinsic motivation, and if you think my mission is important!`

## Mission
The most important reason for me to join the foundation is that I have an intrinsic motivation to lighten the burden for open source maintainers.

Maintainers are people that work incredibly hard. They get home from work, and after their working hours they take time to help *you!*
They are not after fame; they are not after money; they do it out of love for their open source project. Their code is everywhere, and it runs everywhere, yet still they do not get a dime! They have to deal with people raising issues `fix this bug` and `create this feature.` And when they do take time off to look after themselves, they get comments saying `why does this feature take so long?`. It is no wonder that there are some many open sources maintainers burnouts. It is just unhealthy.

If I should be so lucky to join the .NET Foundation as a board member, I will do everything in my power to help these maintainers. One of the things I would like to look into is tooling. This can be anything from CI\CD, to nontechnical, to automatic dependecies updates. I would also like to help them set up a good issue and PR templates by providing best practices, enable them to use bots that can help with there application lifecycle. There is probably a whole lot more things that I cannot think about right now!

Another important point I want to make is that the .NET Foundation should be a open source advocate, we as members and as the board should spread the message about what open source is and who are behind all these great open source products. It is very important to spread awareness about how skewed the open source world is right now, and that it is unsustainable. This can be done by blogging, speaking at conferences and meetups or just talks to your fellow techies at your local company. I believe that if this message ever hits it will benefit all and that it is a goal worth fighting for.

## Passion

My passion is also maintaining and growing open source projects, and this is how I know the burden that can rest on somebody shoulders. I have been a maintainer of [MvvmCross](www.mvvmcross.com), and currently I am a maintainer of [NuKeeper](https://github.com/NuKeeperDotNet/NuKeeper). I love to work on it in technical terms; you can think about new features for the project, fix bugs, and make code improvements. But what I also love is to help other people make their (first) contribution. I have experienced that a lot of people want to contribute back but are too afraid to do so. A simple `Can you make a PR for that? We can help if you join the slack channel` is often enough. It is also a great feeling when people share the love that they have for your open source projects.

I think I am a good fit on the board because I know what it takes to be a maintainer. That being said, I am not the most experienced open source maintainer that is running. Yet, this can be a benefit and can bring in a different perspective from someone who `only` has been doing open source for `3 years`.

## Experience

I have been a professional developer for about three years now; you could say that I am just starting. During my first year, I worked for a Xamarin oriented company. I immediately fell in love with Xamarin, and I was so excited about it, that in that first year I decided to contribute back by [blogging](https://www.marcbruins.nl) and by building a lot of [plugins](https://www.github.com/MarcBruins). During my second year, I was getting more involved with [MvvmCross](https:/www.mvvmcross.com), and eventually, ended up as a maintainer. That was also the first year in which I got my [MVP award](https://mvp.microsoft.com/en-us/PublicProfile/5002791?fullName=Marc%20%20Bruins)! 

Not long ago I stumbled on a new open source project called [NuKeeper](https://github.com/NuKeeperDotNet/NuKeeper) which gets all my open source attention right now. The reason that it is such a cool project is because it aligns with my mission as it gives back time to the maintainers, by automatically updating their dependencies.

## Links

[Twitter](https://www.twitter.com/MarcBruins)
[Github](https://www.github.com/MarcBruins)
[Blog](https://www.marcbruins.nl)

[NuKeeper](https://github.com/NuKeeperDotNet/NuKeeper)
[MvvmCross](www.mvvmcross.com)

**Comment by MarcBruins** [comment]
finally finished 💯

**Comment by jongalloway** [comment]
Closed by https://github.com/dotnet-foundation/election/commit/92fd6a2f06a5a6e92f062ceecc5ab37e145bd21a
