### ISSUE TITLE
Robert McLaws

### ISSUE THREAD

**Issue by robertmclaws** [dotnet-foundation/election#2]
---
title: Robert McLaws, Candidate for .NET Foundation Board
layout: default
---
<div align="center"><img src="https://user-images.githubusercontent.com/1657085/53609747-504f0580-3b96-11e9-979d-0727bcc63f42.png" width=200>
<h1> .NET Foundation Campaign: Robert McLaws</h1>

[![Twitter - Robert McLaws][twitter-img-robert]][twitter-robert]  [![Twitter - CloudNimble][twitter-img-cn]][twitter-cn]
</div>

## About Me
I'm a 36 year old husband to a wonderful wife and father to 3 amazing girls from Tallahassee, FL. I've been programming for as long as I can remember, starting out on Apple IICs in the early 90's... and have neen a professional developer my entire adult life.

I'm currently CEO of CloudNimble, Inc., a consulting firm that specializes in Microsoft technologies. We're modernizing DevOps for the State of Florida, spearheading upgrades to the Agency for Health Care Administration, including a modern enterprise application that helps the agency investigate Medicaid abuse. But my passion is helping startups, which is why we're building [🔥 **BurnRate**](https://burnrate.io), an ASP.NET Core app that helps startups scale out their sales teams.

## Why I'm Running
I've been developing on the .NET Framework my entire professional career. I've had dozens of opportunities to help shape the platform over the years, from the Whidbey Alpha Design Reviews back in 2002, to my contributions to OData and Restier today. The .NET Foundation is doing important work in furthering Microsoft's OSS contributions, and with my focus on developer experiences and simplicity, I feel like I can help make an impact on product quality across the .NET Ecosystem.

## My .NET Contributions
- **Five-time Microsoft MVP across 3 different technologies, ASP.NET, .NET Framework, and Windows**
  - Was the youngest Developer MVP at the time of my first award in 2003
- **Built the first Scrollable DataGrid component for ASP.NET 1.0**
  - [ScrollingGrid product site via The Wayback Machine](https://web.archive.org/web/20040603050441/http://www.interscapeusa.com/Products/ScrollingGrid/)
- **Built the first DataSet -> Excel export library for .NET 1.0.**
  - [GenX.NET product site via The Wayback Machine](https://web.archive.org/web/20040603043814/http://www.interscapeusa.com/Products/GenX/)
- Helped shape ASP.NET 2.0 & Visual Studio 2005 through the private Whidbey Design Review program.
- **Ran the first blogging community for Windows (LonghornBlogs.com)**
  - Featured lots of content on .NET 2.0 and 3.0
  - Winner, PC Magazine's Top 100 Websites of 2004

## My .NET OSS Contributions
- **Ported Zlib to a Portable Class Library**
  - Was a dependency in the core library that backed all of Google's .NET APIs for 2 years
- **Ported Mono's implementation of the Task Parallel Library to a Portable Class Library as [System.Threading.Tasks](https://www.nuget.org/packages/System.Threading.Tasks/)**
  - Compatibility for multithreaded apps on Windows Phone 8 and later
  - Today, the package is the only System.* NuGet package to bear another owner's name
- **My NuGet packages have nearly 56M downloads on NuGet.org**
- **First non-employee to be given Contributor access to Microsoft's OData repo**
- **First non-employee (along with @cwoodruff) to be put in charge of a Microsoft OSS project (https://github.com/odata/restier).**

## Links
* [My old .NET blog](https://weblogs.asp.net/rmclaws)
* [Microsoft OData](https://github.com/odata)
* [Microsoft Restier](https://github.com/odata/restier)
* GitHub profile for my previous company: @advancedrei
* NuGet Profile #1: https://www.nuget.org/profiles/AdvancedREI
* NuGet Profile #2: https://www.nuget.org/profiles/CloudNimble

## Contact Information
* GitHub #1: @RobertMcLaws
* GitHub #2: @CloudNimble

[twitter-robert]:https://twitter.com/robertmclaws
[twitter-cn]:https://twitter.com/cloud_nimble
[code-of-conduct]:https://opensource.microsoft.com/codeofconduct/

[github-version-img]:https://img.shields.io/github/release/ryanoasis/nerd-fonts.svg?style=for-the-badge
[gitter-img]:https://img.shields.io/gitter/room/nwjs/nw.js.svg?style=for-the-badge
[code-climate-img]:https://img.shields.io/codeclimate/issues/github/ryanoasis/nerd-fonts.svg?style=for-the-badge
[code-of-conduct-img]: https://img.shields.io/badge/code%20of-conduct-00a1f1.svg?style=for-the-badge&logo=windows
[twitter-img-robert]:https://img.shields.io/badge/twitter-@robertmclaws-55acee.svg?style=for-the-badge&logo=twitter
[twitter-img-cn]:https://img.shields.io/badge/twitter-@cloud__nimble-55acee.svg?style=for-the-badge&logo=twitter

**Comment by jongalloway** [comment]
Closed via https://github.com/dotnet-foundation/election/commit/6179c96f4e82c5c37cd45b4aab0ba24ce340b987

Had to tweak content at the top since jekyll / github pages doesn't handle markdown inside of HTML blocks.

Permalink is here: https://election.dotnetfoundation.org/campaign-2019/robert-mclaws.html

Thanks for your submission!

**Comment by robertmclaws** [comment]
Sorry about that, thanks for making it work :)
