### ISSUE TITLE
Campaign Statement: Toni Solarin-Sodara

### ISSUE THREAD

**Issue by tonerdo** [dotnet-foundation/election#21]
---
title: Toni Solarin-Sodara
layout: default
---

# .NET Foundation Campaign: Toni Solarin-Sodara

![toni solarin-sodara](https://avatars.githubusercontent.com/tonerdo?size=220)

## Why I'm Running
I unapologetically love .NET and with that love comes the desire to have a hand in shaping its future. If elected, I plan to champion initiatives in the following key areas:

### Foundation Endorsed Projects

For many, the move from proprietary .NET to its open-source world has been quite painful because the libraries and tools they depend on, haven't made the jump themselves. This initiative will aim to engage teams of volunteers from the wider .NET community to build open source ports and greenfield projects, that plug the holes in the development experience. It will also aim to foster open source culture by increasing confidence in community created tools and reducing reliance on proprietary "official" solutions.

### Ecosystem Integration

As we work on growing the .NET community, especially in the underserved regions, we need to be reminded that we cannot function in isolation from other communities. For open-source .NET to fully thrive, we need to get rid of the widespread impression that it should only be used when working with Microsoft platforms (like Windows and Azure). This initiative will facilitate and support documentation, conference talks, projects and more, that demonstrate the use of .NET with non-Microsoft platforms and push the right narrative that .NET is truly a platform for building anything, anywhere.

## My .NET Contributions

I'm a Microsoft MVP and the lead maintainer of [Coverlet](https://github.com/tonerdo/coverlet), a popular open-source cross-platform code coverage tool for the .NET platform. Amongst other projects I contribute to, I also work on native interop and runtime code generation on an experimental .NET runtime called [CoreRT](https://github.com/dotnet/corert).

When not working on open source projects, you can find me organizing and speaking at meetups or conferences, on topics specific to open source with .NET Core.

## Links
* [Blog](https://medium.com/@tonerdo)
* Open Source
  * [Coverlet](https://github.com/tonerdo/coverlet)
  * [ReadLine](https://github.com/tonerdo/readline)
  * [CoreRT](https://github.com/dotnet/corert/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Atonerdo)
  * [Pose](https://github.com/tonerdo/pose)
  * [Microsoft Docs](https://github.com/dotnet/docs/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Atonerdo)
* Meetup Groups/Talks
  * [.NET Lagos](https://twitter.com/dotnetlagos)
  * [DotnetConf 2018](https://channel9.msdn.com/Events/dotnetConf/2018/S302)
  * [Microsoft Ignite 2018](https://www.youtube.com/watch?v=b9wN-UPg-AE)

## Contact Information
* Twitter: [@tonerdo](https://twitter.com/tonerdo)
* GitHub: [@tonerdo](https://github.com/tonerdo)

**Comment by jongalloway** [comment]
Closed by https://github.com/dotnet-foundation/election/commit/852b646835bb9c6644a98a664ac4b7a2359613f2
