### ISSUE TITLE
Ginny Caughey: Campaign Statement

### ISSUE THREAD

**Issue by gcaughey** [dotnet-foundation/election#22]
------------------------------------------------------------------------------------

---
title: Ginny Caughey
layout: default
---

# .NET Foundation Campaign: Ginny Caughey

## Why I'm Running
![build2019headshot 50jpg](https://user-images.githubusercontent.com/6218283/53746947-38b29e00-3e70-11e9-982a-a0ddb0a9134b.jpg)

I've been building applications that rely on .NET since version 1.0 and can gratefully say that my company owes its success to .NET in an important way. I'm now responsible for maintaining and enhancing .NET-based applications using Windows Forms and WPF relied on by local governments and enterprises all over the United States and Canada. (https://www.wasteworksonline.com/about/)

Because my company's customers are large and small, governmental and private, multi-national and single-site, I get a lot of varied feedback about their concerns and experiences using the .NET applications that run their enterprises. .NET affects not only developers and IT professionals but also the end users of all those applications. I want to help .NET continue to meet their needs.

## My .NET Contributions
My first experience with Open Source was as a founding member of OpenNETCF (http://opennetcf.org/about-opennetcf/) That was a project for .NET's little sister .NET Compact Framework and its mission was to provide "missing" functionality mainly using P/Invoke to Windows CE APIs. That was so long ago that Microsoft engineers were not even allowed to visit our site at the time!

Fortunately times have changed a lot and more recently I've been involved with the Windows Community Toolkit (https://github.com/windows-toolkit/WindowsCommunityToolkit), 

I was such a noisy complainer about missing SqlClient support in .NET Standard used by UWP apps that I was invited to present at the Build conference the year that support was announced. (https://channel9.msdn.com/Events/Build/2017/B8012) I also presented an updated version of that session at Ignite (https://channel9.msdn.com/Events/Ignite/Microsoft-Ignite-Orlando-2017/BRK2069) This experience convinced me that my needs and opinions mattered.

This year I've been testing .NET Core 3.0 against my suite of production enterprise applications and look forward to working with improved Visual Studio tooling for Windows Forms and WPF using .NET Core 3.0.

## Links
* MVP page https://mvp.microsoft.com/en-us/PublicProfile/7909?fullName=Ginny%20Caughey
* Build 2018 MC https://developer.microsoft.com/en-us/events/build/build-mc-commercial
* Windows Community Toolkit https://github.com/windows-toolkit/WindowsCommunityToolkit

## Contact Information
* Twitter: @gcaughey 
* GitHub: @gcaughey

**Comment by MarcBruins** [comment]
Just say your profile and notice the links where broken. Would be good to update those!

**Comment by gcaughey** [comment]
Thanks – will do!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gcaughey** [comment]
> Just say your profile and notice the links where broken. Would be good to update those!

They seem ok for me now. Can you confirm please? Thanks.

**Comment by daveaglick** [comment]
I can confirm - none of the links are rendering as links:

![2019-03-04_14h12_51](https://user-images.githubusercontent.com/1020407/53756633-9b636400-3e87-11e9-8988-64ad0cbc1709.png)
