### ISSUE TITLE
.NET Foundation Campaign: Lea Wegner

### ISSUE THREAD

**Issue by Luminca** [dotnet-foundation/election#25]
# .NET Foundation Campaign: Lea Wegner

## Why I'm Running
Hey, i'm Lea Wegner and i'm a dual computer science student from germany. 
The dual study system gives me the oppurtunity to work in the software industry since my beginning in 2017. To be honest i did not worked with .NET at this point, but i'm interested in learning new things and can bring you my unimpaired opinions, the view of a student and a newcomer, and the knowledge about how it is to work in germany as a young woman in the software industry.

## Contact Information
* Email: lea_wegner@gmx.de

**Comment by jongalloway** [comment]
Got this submission, working with @rachelappel to get the contribution requirement figured out (a requirement to run for a board seat). Happy you're interested, discussion going on via e-mail.

**Comment by Luminca** [comment]
Thanks for your answer, just made a little change here https://github.com/dotnet/samples/compare/master...Luminca:patch-1
Hope to hear from you again :)

**Comment by jongalloway** [comment]
@Luminca I just posted. Sorry for the delay, had to get the membership approved. Feel free to update your statement by editing this: https://github.com/dotnet-foundation/election/blob/master/_campaign-2019/lea-wegner.md

cc @rachelappel
