### ISSUE TITLE
.NET Foundation Campaign: Virgile Bello

### ISSUE THREAD

**Issue by xen2** [dotnet-foundation/election#31]
---
title: Virgile Bello
layout: default
---

# .NET Foundation Campaign: Virgile Bello

## Why I'm Running

I noticed a lack of candidatures representing the game development field and high-performance .NET.

I believe .NET is a perfect match not only for game development but also various related fields such as AI, language parsing, massively parallel programming (GPU and CPU) and such.

As a result, I would like the .NET Foundation to dedicate some resources to:
* Promote .NET in game development, AI, massively parallel programming and high-performance programming (i.e. be well represented at Game Developer Conferences and various other events)
People in those fields need to be aware .NET could be a valid alternative.
* Encourage the .NET ecosystem to take those use case into account (esp. for CoreCLR/CoreRT directions)
* Encourage support for more platforms (console, mobile, etc.)

## My .NET Contributions

* [Xenko](https://xenko.com): Lead developer of recently opensourced game engine [Xenko](https://xenko.com)
It features realistic rendering, VR, editor and [much more](https://xenko.com/features).

* [SharpLang](https://github.com/xen2/SharpLang): .NET to LLVM compiler and runtime prototype, no longer active since [CoreCLR](https://github.com/dotnet/coreclr) came out)

* Various contributions to open source projects such as Mono, LLDB, etc.

## Links
Xenko:
* [Website](https://xenko.com)
* [Features](https://xenko.com/features)
* [GitHub](https://github.com/xenko3d/xenko)

## Contact Information
* Twitter: [@xen2](https://twitter.com/xen2)
* GitHub: [@xen2](https://github.com/xen2)

**Comment by jongalloway** [comment]
Can you provide a URL to a profile photo? We've mostly been using GitHub or Twitter photo URLs, but neither of your profile photos work for this.

**Comment by xen2** [comment]
Here you go!
https://user-images.githubusercontent.com/527565/54175230-5ebdeb00-44cd-11e9-8b5f-d9b760065e97.jpg

More "square" aspect ratio:
https://user-images.githubusercontent.com/527565/54175449-47333200-44ce-11e9-9e77-90f83816744b.jpg

Also, is it OK to add a quick screenshot and/or logo of Xenko in the campaign text or should it be only text?
