### ISSUE TITLE
Eric Sink

### ISSUE THREAD

**Issue by ericsink** [dotnet-foundation/election#33]
---
title: Eric Sink
layout: default
---

# .NET Foundation Campaign: Eric Sink

## Why I'm Running

So there's the issue of my relatively low level of awesomeness.  Looking over the list of other candidates, I wonder if I will even be able to vote for myself.

So why am I running?  Simple:  I am passionate about .NET.  

I've been using .NET for as long as it has existed.  SourceGear was one of the first ISVs to ship a product written in C#.  Today, seventeen years later, my day is usually spent with things like .NET Core and Xamarin.  I've seen it all, and I believe this:

The best time in history to be a .NET developer is right now.

It has been terribly exciting to watch .NET move toward open source, cross-platform, and mobile.  I think .NET's best days are yet to come.

So if the voters decide that I could be helpful to the .NET community as a foundation board member, I would consider it an honor to serve.

## My favorite stuff

I don't much like technology religion, and I respect varying opinions.  But I figure that folks may want to cast their votes for candidates whose technology interests align with their own.  So...

I love F#.  But I have to admit that I'm rather pragmatic about it.  So for various reasons, I am using a lot of C# right now.  And I love C# too. 

So, if you are an F# fan and are disappointed in my lack of pure devotion, you should probably vote against me.

But I *so* wish F# had more gravity in the .NET community.  So if you are someone who wishes F# would disappear from the earth, you too should not vote for me.

I am also a big fan of Rx.  That tends to be another somewhat-polarizing issue in the .NET community, so my deep fondness for `IObservable` might help you decide whether to vote for me or not.

I love Xamarin.  I use Xamarin Forms, but not XAML.

I use .NET Core, but not Azure.

I prefer spaces over tabs, command line over IDE, vim over emacs, and static typing over dynamic.  

## My .NET Activities and Contributions

I founded SourceGear (a small software company in Illinois) about 22 years ago.  My business partner (Corey Steffen) and I think of ourselves as serial entrepreneurs within a single company.  We do a mix of custom software contracting as well as products of our own.

 - Yes, in 2019, people are *still* switching from SourceSafe to SourceGear Vault.

 - Our mobile data sync solution for SQL Server is called Zumero.

 - Our team built the cross-platform support for Team Foundation Server (under the name Teamprise) and sold it to Microsoft in 2009.

 - Our latest effort is PepTown, a smartphone-based fundraising solution for high school sports teams, built on Xamarin and .NET Core.

I am the maintainer of SQLitePCL.raw, a low-level SQLite wrapper for .NET.  It is widely used as the layer below a number of other libraries, including sqlite-net, Akavache, and Entity Framework Core.

## Links
* [SQLitePCL.raw on GitHub](https://github.com/ericsink/SQLitePCL.raw)
* [An F# rant on my blog](https://ericsink.com/entries/fsharp_chasm.html)
* [not a legend (2003 silliness)](http://notalegend.com/)

## Contact Information
* Twitter: [@eric\_sink](https://twitter.com/eric_sink)
* GitHub: [@ericsink](https://github.com/ericsink)

**Comment by jongalloway** [comment]
I'd like to update with profile photo. We've been using GitHub avatars unless you'd like to use something different, is this okay?

https://avatars2.githubusercontent.com/u/3877005?s=400&v=4

**Comment by ericsink** [comment]
I just replaced my GitHub avatar with something more current.  Hopefully the new pic will work?

**Comment by jongalloway** [comment]
Perfect, updated!
