### ISSUE TITLE
Iris Classon

### ISSUE THREAD

**Issue by IrisClasson** [dotnet-foundation/election#51]
---
title: Iris Classon
layout: default
---

# .NET Foundation Campaign: Iris Classon

## Why I'm Running
Since my very first day as an aspiring programmer, after deciding that clinical nutrition wasn’t for me, I’ve been a passionate and active community member of the .NET community. Since day one, I’ve shared everything I’ve learned, as blog posts, tweets, on forums, conferences, user groups, videos, books and more. While I’ve been predominantly avid about reaching out to students, particularly those with no programming background and minorities (as I can relate), I’ve also been active in giving feedback, submitting issues and contributing directly.

I want to make sure that we keep the community inclusive, and encourage newcomers to take part early on- as contributors, evangelists and active members. I’ve unfortunately seen too many times that organizations in tech can become homogenous and elitist, and I’m confident that I can make sure that we don’t head in that direction. In my short history as a programmer (compared to many of you) I’ve arranged everything from conferences, hackathons, workshops, school material and a whole lot more, for all age groups (including kids and elderly/seniors), mixed backgrounds and levels of difficulty. I know how to reach out, and how to get people excited and engaged, and while I don’t have any open source projects to impress with- I can get people on-board that we will impress us all in the future. That is my strength, and that is why I’m running as a candidate.

## My .NET Contributions
Here is a random selection of things I've done. Wasn't sure what to add, I've done quite a few things. This is a sample to showcase my passion and reach:

Things without links:
I ran for two years a study group (.NET) Meetup with 300 members that later became the model for similar study groups. The meetup was hosted and organized by me twice a month, and we used e-learning tools to learn new topics and tools with a mob-programming approach.

BUILD MC at BUILD last year- that was fun!

Organized and ran Azure Global Bootcamp several times, in addition to several free workshops for schools/unis. 

Volunteered as a judge on several panels such as NASA Space App Challenge and youth competitions.

Co-hosted the GetUpAndCode! podcast for a year with close to 50 episodes [Podcast on ITunes](https://itunes.apple.com/us/podcast/get-up-and-code/id646958161?mt=2)

Not sure if it matters in this context, but I've made the top 100 most influential tech Women on Twitter (Business Insider, placed 58th) and top 50 best developers in Sweden (23rd place, TechWorld Sweden). I can't say I necessarily agree with the above, but I hope this shows that I have good reach. 

## (Some) Links
* [My blog. Less activity last 1-2 months as I have a newborn](http://irisclasson.com)
* [Channel9- Interviews, conference sessions and more](https://channel9.msdn.com/Search?term=iris%20classon&lang-en=true)
* [Vimeo- recorded conference sessions](https://vimeo.com/search?q=iris%20classon)
* [YouTube](https://www.youtube.com/channel/UChUJLb50mNALThfUuZZn7QA)

## Contact Information
* Twitter: [@irisclasson](https://twitter.com/irisclasson)
* StackOverflow: [@irisclasson](https://stackoverflow.com/users/984153/iris-classon)
* GitHub: [@irisclasson](https://github.com/irisclasson)

I've omitted paid contributions such as e-learning courses, books and talks (keynotes)

**Comment by jongalloway** [comment]
Okay to update with your profile picture? I can use https://avatars2.githubusercontent.com/u/1671084?s=400&v=4

**Comment by IrisClasson** [comment]
Go for it! Current hair color is dark brown :) Any photo that matches would work haha

**Comment by jongalloway** [comment]
So which is best - GitHub, Twitter, or got a link? Most people are using GitHub avatars but any URL works.
