### ISSUE TITLE
.NET Foundation Campaign: David Dieruf

### ISSUE THREAD

**Issue by ddieruf** [dotnet-foundation/election#60]
---
title: David Dieruf
layout: default
image: https://drive.google.com/file/d/1WjfkKo58lx8Dr6UxwtQod64O9Y5SP32L/view?usp=sharing
---

# .NET Foundation Campaign: David Dieruf

As a developer I have worked within the .NET runtime for many years. With so much history I have a solid understanding of what "traditional .NET" looks like. Things like a developer's IDE, the infrastructure apps run on, the policies surrounding and influencing IT are just a few of those traditional perspectives.

A challenge almost everyone in the .NET community is facing today is, what do those traditional decisions look like in a modern open-sourced world? Our north star for a long time has been Microsoft, but with the opportunity of extending and possibly creating new options we need a guiding opinion to help make those same decisions. I believe the .NET Foundation is that trusted source.

## Why I'm Running

As a Pivot bringing a .NET perspective to one of the largest open sourced projects in the world ([Cloud Foundry](https://cloudfoundry.org)), I have the unique opportunity of helping to guide Microsoft based Organizations on their cloud-native journey. Translating customer feedback and challenges into product features, helping developer teams adapt their thinking to more modern .NET ways, and publishing cloud-native .NET practices are a few examples of my day to day passion to grow open source .NET.

As a .NET Foundation board member I can bring those same experiences and passion, to help the greater .NET community understand OSS and embrace its possibilities. Organizing committees, being a part of committees, and enabling members to communicate the Foundation's message are all areas I am comfortable with.

Thru a combination of my years writing C#, my passion for all things .NET, and my daily interaction with Enterprises in many industries I believe I can be a strong supporting member of the Board. 

## The .NET Foundation - my vision

As a trusted source to the .NET community, the .NET Foundation offers developers the ability to safely and fairly post projects for the world to enjoy and provide the best projects to choose from in a legal manner. 

Bringing open development and collaboration to the .NET community isn’t just cloud apps or services, it’s embracing an ecosystem of technology that is created and grown by the .NET community. Backing services, log aggregation, app metrics, microservice frameworks are just a few examples of open source projects growing the .NET community.

Open sourced .NET is just the opening chapter. The ability to fork or extend the entire .NET runtime is something we’ve never seen before, but the story only starts with this first chapter. The .NET Foundation ensures there are many other chapters in a modern .NET Developer’s book. Stories around creating and making an idea available to the world, options to discover others ideas, extend them, or simply implementing those ideas in their own projects.

The .NET Foundation is the ecosystem to enable, understand, and embrace open source .NET.

## Thank You

The .NET community has begun a remarkable time, where I believe we have an opportunity to make .NET the preferred runtime for all things. I also believe the .NET Foundation will be at the core of this Renaissance. As a technologist, to have the opportunity to be a part of these times is truly inspiring.

## .NET Foundation Contributions

I work closely with the [Steeltoe](https://steeltoe.io) team to help guide, document, and evangelize the wonderful things this project offers to cloud-native .NET. I also advocate for the use of Windows Server container technologies within Cloud Foundry and Kubernetes.

## Organizations I have been a member of
* [Crusade Ambassadors](https://whascrusade.org/whas-crusade-for-children-community-engagement-council/)
* Sawyer Hayes Foundation

## Links
* [My \[public\] work at Pivotal](https://content.pivotal.io/authors/david-dieruf)
* [Steeltoe Article](https://thenewstack.io/steeltoe-modernize-net-apps-for-a-microservices-architecture/)

## Contact Information
* Twitter: [@dierufdavid](https://twitter.com/dierufdavid)
* GitHub: [@ddieruf](https://github.com/ddieruf)
* Linkedin: [@ddieruf](https://www.linkedin.com/in/ddieruf/)

**Comment by jongalloway** [comment]
Adding image since Google Drive share isn't working for img reference

![David-head-shot](https://user-images.githubusercontent.com/68539/54227549-637aa300-44bd-11e9-8b88-bdd2c9060684.png)
