### ISSUE TITLE
FYI: We now have an elections chat site (gitter.im) open!

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/election#65]
FYI, @jongalloway created https://gitter.im/dotnet-foundation/election so everyone would have a place to chat, answer questions informally, etc.

I'm inviting everyone here who has contributed to the repo so you're notified and can hopefully jump in and have a chance to speak / ask.

I believe I've captured everyone but apologies if I've somehow missed someone. Also, I appreciate everyone's understanding of the general "potential spammyness" of this message. Wanted to make sure we got the word out quickly.

I will work to parse this into a list of `@candidates` so that @jongalloway can turn it into a group and people can ask us issues right on the repo.

-----

## Added Because You've submitted an issue that's since been closed
@mairaw 
@ddieruf
@IEvangelist
@stefanov-stefan
@IrisClasson
@Ant-hem 
@samidip 
@LuceCarter
@rdiazconcha 
@Mpdreamz
@schneidenbach 
@mitchelsellers
@pmbanugo 
@prkhandelwal
@ericsink
@ErikSchierboom 
@xen2
@mhutch
@gcaughey
@tonerdo
@daveaglick
@jskeet 
@MarcBruins 
@jguadagno 
@Haacked 
@dotMorten 
@sbwalker
@AndreyAkinshin
@glennawatson
@devlead
@stevejgordon 
@onovotny

## Added Because you have a currently open issue on the repo
@Lakritzator 
@tidusjar 
@shana 
@Luminca 
@ghuntley 

## Added Because You've Submitted a PR
@schneidenbach 
@stevejgordon
@SeanKilleen
@rdiazconcha 
@mhutch 
@khalidabuhakmeh 
@ErikSchierboom 
@daveaglick
@glennawatson
@MarcBruins
@onovotny
@devlead 
@robertmclaws

**Comment by jongalloway** [comment]
@dotnet-foundation/candidates is set up, so you should get notification via this, too.

Thanks, @SeanKilleen!

**Comment by MeikTranel** [comment]
testing @dotnet-foundation/candidates

**Comment by SeanKilleen** [comment]
@meiktranel it works :)

**Comment by stevejgordon** [comment]
Got it!

Best Regards,
Steve Gordon

Microsoft MVP - Developer Technologies
Twitter: @stevejgordon
https://www.stevejgordon.co.uk


________________________________

**Comment by SeanKilleen** [comment]
Closing this now as the gitter link is on the election site and this was mostly to notify candidates, who have since been notified. 👍 thanks all!
