### ISSUE TITLE
@Candidates list

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/election#66]
@jongalloway I went through and pulled out everyone who has had their candidacy markdown file added to the election folder. You'd need to add anyone who you merge / add after this, but it's a good place to start.

My aim: being able to create a GH issue, mention `@candidates`, label as `campaign-question` or similar, and allow candidates to answer.

```
@xen2
@tonerdo
@stevejgordon
@stefanov-stefan
@schneidenbach
@sbwalker
@SeanKilleen 
@samidip
@rdiazconcha
@RobertMcLaws
@prkhandelwal
@haacked
@pmbanugo
@onovotny
@dotMorten
@mitchelsellers
@mhutch
@devlead
@Mpdreamz
@MarcBruins
@mairaw
@LuceCarter
@jguadagno
@jskeet
@irisclasson
@glennawatson
@gcaughey
@erikschierboom
@ericsink
@IEvangelist
@ddieruf
@daveaglick
@Ant-hem
@AndreyAkinshin
```

OK, I think that's everyone.

**Comment by jongalloway** [comment]
Created! @dotnet-foundation/candidates 

Closing this issue. Thanks so much, @SeanKilleen!
