### ISSUE TITLE
Test question

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/election#70]
_To test the auto-labeling to ensure it is applied and that others don't see a blank list when searching for questions_ 

## Question
How much wood could a woodchuck chuck if a woodchuck could chuck wood?

**Comment by SeanKilleen** [comment]
> New York state wildlife expert Richard Thomas found that a woodchuck could (and does) chuck around 35 cubic feet of dirt in the course of digging a burrow. Thomas reasoned that if a woodchuck could chuck wood, he would chuck an amount equivalent to the weight of the dirt, or 700 pounds.

([Source](https://mylandplan.org/content/how-much-wood-would-woodchuck-chuck-if-woodchuck-could-chuck-wood))

**Comment by daveaglick** [comment]
That’s a great answer @SeanKilleen and a good place to start. I wouldn’t go so far as to chuck those numbers out the window, but I also think we need to consider the individual wood chuck. Not all wood chucks could chuck wood at the same rate and there may be very good reasons why a wood chuck could chuck different amounts of wood.

**Comment by jongalloway** [comment]
I'm not a candidate, but do feel like it's important we understand this at a deeper level. 

* *Why* would a woodchuck chuck wood?
* What can we *do* to empower more woodchucks to chuck wood?
* Is chucking wood the real problem here?
* Should woodchucks be doing something else - are they only chucking wood because that's what society expects of them?

@dotnet-foundation/candidates - what are your thoughts on this matter?

**Comment by dotMorten** [comment]
I'm going to be honest and acknowledge that I'm no expert on woodchuckers or chucking wood - I mean I can hardly read the question out loud without tying a knot on my tongue. I'd say instead that we should form a subcommittee of people who has intricate knowledge of these very important things, and listen to and support their ideas on how we can help woodchuckers grow in the wood chucking ecosystem, while keeping plenty of wood to chuck for everyone else who may be so inclined.

**Comment by ericsink** [comment]
42

**Comment by khalidabuhakmeh** [comment]
Wood is so 2018

**Comment by robertmclaws** [comment]
![image](https://mondrian.mashable.com/2013%252F09%252F17%252Ff8%252FMr.Woodchuc.01892.gif%252Ffit-in__1200x9600.gif?signature=cDHLiFSOqAsKYIYyyIW8wSiHe-w=)

**Comment by SeanKilleen** [comment]
Given that we have some real questions now, I'm going to go ahead and close this. :)
