### ISSUE TITLE
Glenn Watson Campaign Statement

### ISSUE THREAD

**Issue by glennawatson** [dotnet-foundation/election#8]
---
title: Glenn Watson
layout: default
---

# .NET Foundation Campaign: Glenn Watson

## Why I'm Running
Given that I have a active involvement in numerous DotNet Foundation projects I want to bring solutions to problems I've experienced while at the same time helping out further members of the community.

## My .NET Contributions
* ReactiveUI lead maintainer - August 2018 https://reactiveui.net
* ReactiveGIT - git client for .NET
* GitLfsCachingServer - a local cache for GIT LFS repositories.

## Links
* [My blog](https://glennwatson.net)
* [ReactiveUI](https://reactiveui.net)

## Contact Information
* Twitter: [@GlennCoder](https://twitter.com/GlennCoder)
* GitHub: [@glennawatson](https://github.com/glennawatson)

**Comment by ghuntley** [comment]
Vouching for Glenn. He's been doing a great job with reactiveui.
