### ISSUE TITLE
.NET Foundation Campaign: Daron Yondem

### ISSUE THREAD

**Issue by daronyondem** [dotnet-foundation/election#81]
# Why I’m Running

I saw no representation in the list of candidates from Middle-East, and that killed my imposter syndrome. I have lead INETA Turkey for four years, and INETA MEA for another till Microsoft stopped supporting INETA. I love to work with communities, help them reach larger audiences, build quality events. I have a good understanding of the community in MEA, visit at minimum 6 countries in the region every year to speak in an event. I present to pretty mixed audiences including professional developers, students, and CxOs. That gives me a good understanding of the needs of different types of roles. 

I think there are a couple of areas where Microsoft can do better. Here are some areas I would love to work, fight to improve. 

* Breadth community outreach to regions where English is not the primary language is one of them. Organizing online events and expecting to reach all regions might cover a relatively large percentage of the pie, however, we can do more. 
* Offline localized events can't be successfully driven with small subs. Most of the countries in MEA don't have the resources to organize local versions of Microsoft events. Some don't even have enough expert speakers to run there events. For these locations, offline access is critical as well. You can't simply run a global online event and expect to have the human touch with developers who do not even speak your language. Local experts need to be empowered to build their communities. 
* Student outreach is lacking. Both MSP Program and Imagine Cup seem to get disconnected from communities in MEA. The depth approach is killing the community on this front as well. Microsoft Corp is selecting universities to one-to-one manage and get involved with. What's being done has its reasons, but it is creating a form of inequality of opportunity. Students in unmanaged universities are being welcomed by Google with their Google Developer Days events and GDG communities. These student groups are not being cared for by Microsoft locally. International outreach is not a fix on this front as well. 

# My .NET Contributions

* Led INETA Turkey for 4 years.
* Led INETA MEA for one year.
* MVP for 11 years
* RD for 10 years

You can't be humble if you are asked to show your contributions right? With that said, I honestly don't know how to quantify the amount of speaking, writing, mentorship I did during the last 10+ years. I have written 5 books, spoke at various roadshows in MEA (latest DevOps Roadshow in 5 countries), international conferences (TechEds, MSDays and many more), hosted dozens of trainings, visited 100+ cities to talk about .NET.  

# Links

- [11 Years of Turkish blogging archive](https://github.com/daronyondem/daron-turkce-blog)
- [Current English Blog](https://daron.blog/)
- [Github @daronyondem](https://github.com/daronyondem)
- [11 years of presentations](https://speakerdeck.com/daronyondem)
- [RD Profile](https://rd.microsoft.com/en-us/daron-yondem)
- [MVP Profile](https://mvp.microsoft.com/en-us/PublicProfile/4015692?fullName=Daron%20Yondem)

# Contact Information
- [Twitter @daronyondem](https://twitter.com/daronyondem)
- [LinkedIn](https://www.linkedin.com/in/daronyondem/)

**Comment by jongalloway** [comment]
Closed by https://github.com/dotnet-foundation/election/commit/246a13c41b0c262d2a093c56cb21cda85090ebd5
